// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: arcadia/wallet/v1/wallet.proto

package walletv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WalletService_GetMyWallet_FullMethodName    = "/arcadia.wallet.v1.WalletService/GetMyWallet"
	WalletService_GetWallet_FullMethodName      = "/arcadia.wallet.v1.WalletService/GetWallet"
	WalletService_InitiateCharge_FullMethodName = "/arcadia.wallet.v1.WalletService/InitiateCharge"
	WalletService_RedeemGiftCard_FullMethodName = "/arcadia.wallet.v1.WalletService/RedeemGiftCard"
	WalletService_ListLedger_FullMethodName     = "/arcadia.wallet.v1.WalletService/ListLedger"
	WalletService_Debit_FullMethodName          = "/arcadia.wallet.v1.WalletService/Debit"
	WalletService_Credit_FullMethodName         = "/arcadia.wallet.v1.WalletService/Credit"
	WalletService_Transfer_FullMethodName       = "/arcadia.wallet.v1.WalletService/Transfer"
	WalletService_HoldFunds_FullMethodName      = "/arcadia.wallet.v1.WalletService/HoldFunds"
	WalletService_CaptureHold_FullMethodName    = "/arcadia.wallet.v1.WalletService/CaptureHold"
	WalletService_ReleaseHold_FullMethodName    = "/arcadia.wallet.v1.WalletService/ReleaseHold"
	WalletService_ListHolds_FullMethodName      = "/arcadia.wallet.v1.WalletService/ListHolds"
)

// WalletServiceClient is the client API for WalletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalletServiceClient interface {
	// Returns the caller's own wallet, provisioning it on first access.
	GetMyWallet(ctx context.Context, in *GetMyWalletRequest, opts ...grpc.CallOption) (*GetMyWalletResponse, error)
	// Returns any wallet by user id. Requires SUPPORT or ADMIN.
	GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*GetWalletResponse, error)
	// Starts a bank top-up: creates a payment intent through the Payment Adapter
	// and hands the redirect URL back to the client. The balance only changes
	// once BankPaymentConfirmed arrives over Kafka.
	InitiateCharge(ctx context.Context, in *InitiateChargeRequest, opts ...grpc.CallOption) (*InitiateChargeResponse, error)
	RedeemGiftCard(ctx context.Context, in *RedeemGiftCardRequest, opts ...grpc.CallOption) (*RedeemGiftCardResponse, error)
	ListLedger(ctx context.Context, in *ListLedgerRequest, opts ...grpc.CallOption) (*ListLedgerResponse, error)
	Debit(ctx context.Context, in *DebitRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
	Credit(ctx context.Context, in *CreditRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
	// Atomic debit-of-one-wallet + credit-of-another, used for marketplace trade
	// settlement. Either both sides move or neither does.
	Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error)
	// --- Holds (pre-orders and instalments) --------------------------------
	HoldFunds(ctx context.Context, in *HoldFundsRequest, opts ...grpc.CallOption) (*HoldFundsResponse, error)
	CaptureHold(ctx context.Context, in *CaptureHoldRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
	ReleaseHold(ctx context.Context, in *ReleaseHoldRequest, opts ...grpc.CallOption) (*ReleaseHoldResponse, error)
	ListHolds(ctx context.Context, in *ListHoldsRequest, opts ...grpc.CallOption) (*ListHoldsResponse, error)
}

type walletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletServiceClient(cc grpc.ClientConnInterface) WalletServiceClient {
	return &walletServiceClient{cc}
}

func (c *walletServiceClient) GetMyWallet(ctx context.Context, in *GetMyWalletRequest, opts ...grpc.CallOption) (*GetMyWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyWalletResponse)
	err := c.cc.Invoke(ctx, WalletService_GetMyWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*GetWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletResponse)
	err := c.cc.Invoke(ctx, WalletService_GetWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) InitiateCharge(ctx context.Context, in *InitiateChargeRequest, opts ...grpc.CallOption) (*InitiateChargeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateChargeResponse)
	err := c.cc.Invoke(ctx, WalletService_InitiateCharge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) RedeemGiftCard(ctx context.Context, in *RedeemGiftCardRequest, opts ...grpc.CallOption) (*RedeemGiftCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RedeemGiftCardResponse)
	err := c.cc.Invoke(ctx, WalletService_RedeemGiftCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ListLedger(ctx context.Context, in *ListLedgerRequest, opts ...grpc.CallOption) (*ListLedgerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLedgerResponse)
	err := c.cc.Invoke(ctx, WalletService_ListLedger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) Debit(ctx context.Context, in *DebitRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, WalletService_Debit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) Credit(ctx context.Context, in *CreditRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, WalletService_Credit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferResponse)
	err := c.cc.Invoke(ctx, WalletService_Transfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) HoldFunds(ctx context.Context, in *HoldFundsRequest, opts ...grpc.CallOption) (*HoldFundsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HoldFundsResponse)
	err := c.cc.Invoke(ctx, WalletService_HoldFunds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) CaptureHold(ctx context.Context, in *CaptureHoldRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, WalletService_CaptureHold_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ReleaseHold(ctx context.Context, in *ReleaseHoldRequest, opts ...grpc.CallOption) (*ReleaseHoldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseHoldResponse)
	err := c.cc.Invoke(ctx, WalletService_ReleaseHold_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ListHolds(ctx context.Context, in *ListHoldsRequest, opts ...grpc.CallOption) (*ListHoldsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHoldsResponse)
	err := c.cc.Invoke(ctx, WalletService_ListHolds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServiceServer is the server API for WalletService service.
// All implementations should embed UnimplementedWalletServiceServer
// for forward compatibility.
type WalletServiceServer interface {
	// Returns the caller's own wallet, provisioning it on first access.
	GetMyWallet(context.Context, *GetMyWalletRequest) (*GetMyWalletResponse, error)
	// Returns any wallet by user id. Requires SUPPORT or ADMIN.
	GetWallet(context.Context, *GetWalletRequest) (*GetWalletResponse, error)
	// Starts a bank top-up: creates a payment intent through the Payment Adapter
	// and hands the redirect URL back to the client. The balance only changes
	// once BankPaymentConfirmed arrives over Kafka.
	InitiateCharge(context.Context, *InitiateChargeRequest) (*InitiateChargeResponse, error)
	RedeemGiftCard(context.Context, *RedeemGiftCardRequest) (*RedeemGiftCardResponse, error)
	ListLedger(context.Context, *ListLedgerRequest) (*ListLedgerResponse, error)
	Debit(context.Context, *DebitRequest) (*TransactionResponse, error)
	Credit(context.Context, *CreditRequest) (*TransactionResponse, error)
	// Atomic debit-of-one-wallet + credit-of-another, used for marketplace trade
	// settlement. Either both sides move or neither does.
	Transfer(context.Context, *TransferRequest) (*TransferResponse, error)
	// --- Holds (pre-orders and instalments) --------------------------------
	HoldFunds(context.Context, *HoldFundsRequest) (*HoldFundsResponse, error)
	CaptureHold(context.Context, *CaptureHoldRequest) (*TransactionResponse, error)
	ReleaseHold(context.Context, *ReleaseHoldRequest) (*ReleaseHoldResponse, error)
	ListHolds(context.Context, *ListHoldsRequest) (*ListHoldsResponse, error)
}

// UnimplementedWalletServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWalletServiceServer struct{}

func (UnimplementedWalletServiceServer) GetMyWallet(context.Context, *GetMyWalletRequest) (*GetMyWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyWallet not implemented")
}
func (UnimplementedWalletServiceServer) GetWallet(context.Context, *GetWalletRequest) (*GetWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWallet not implemented")
}
func (UnimplementedWalletServiceServer) InitiateCharge(context.Context, *InitiateChargeRequest) (*InitiateChargeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateCharge not implemented")
}
func (UnimplementedWalletServiceServer) RedeemGiftCard(context.Context, *RedeemGiftCardRequest) (*RedeemGiftCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RedeemGiftCard not implemented")
}
func (UnimplementedWalletServiceServer) ListLedger(context.Context, *ListLedgerRequest) (*ListLedgerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLedger not implemented")
}
func (UnimplementedWalletServiceServer) Debit(context.Context, *DebitRequest) (*TransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Debit not implemented")
}
func (UnimplementedWalletServiceServer) Credit(context.Context, *CreditRequest) (*TransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Credit not implemented")
}
func (UnimplementedWalletServiceServer) Transfer(context.Context, *TransferRequest) (*TransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Transfer not implemented")
}
func (UnimplementedWalletServiceServer) HoldFunds(context.Context, *HoldFundsRequest) (*HoldFundsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HoldFunds not implemented")
}
func (UnimplementedWalletServiceServer) CaptureHold(context.Context, *CaptureHoldRequest) (*TransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CaptureHold not implemented")
}
func (UnimplementedWalletServiceServer) ReleaseHold(context.Context, *ReleaseHoldRequest) (*ReleaseHoldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseHold not implemented")
}
func (UnimplementedWalletServiceServer) ListHolds(context.Context, *ListHoldsRequest) (*ListHoldsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHolds not implemented")
}
func (UnimplementedWalletServiceServer) testEmbeddedByValue() {}

// UnsafeWalletServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletServiceServer will
// result in compilation errors.
type UnsafeWalletServiceServer interface {
	mustEmbedUnimplementedWalletServiceServer()
}

func RegisterWalletServiceServer(s grpc.ServiceRegistrar, srv WalletServiceServer) {
	// If the following call pancis, it indicates UnimplementedWalletServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WalletService_ServiceDesc, srv)
}

func _WalletService_GetMyWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetMyWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_GetMyWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetMyWallet(ctx, req.(*GetMyWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_GetWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetWallet(ctx, req.(*GetWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_InitiateCharge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateChargeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).InitiateCharge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_InitiateCharge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).InitiateCharge(ctx, req.(*InitiateChargeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_RedeemGiftCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedeemGiftCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).RedeemGiftCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_RedeemGiftCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).RedeemGiftCard(ctx, req.(*RedeemGiftCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ListLedger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLedgerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ListLedger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_ListLedger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ListLedger(ctx, req.(*ListLedgerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_Debit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DebitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).Debit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_Debit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).Debit(ctx, req.(*DebitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_Credit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).Credit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_Credit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).Credit(ctx, req.(*CreditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_Transfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).Transfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_Transfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).Transfer(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_HoldFunds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HoldFundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).HoldFunds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_HoldFunds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).HoldFunds(ctx, req.(*HoldFundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_CaptureHold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureHoldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).CaptureHold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_CaptureHold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).CaptureHold(ctx, req.(*CaptureHoldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ReleaseHold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseHoldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ReleaseHold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_ReleaseHold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ReleaseHold(ctx, req.(*ReleaseHoldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ListHolds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHoldsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ListHolds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_ListHolds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ListHolds(ctx, req.(*ListHoldsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletService_ServiceDesc is the grpc.ServiceDesc for WalletService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arcadia.wallet.v1.WalletService",
	HandlerType: (*WalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMyWallet",
			Handler:    _WalletService_GetMyWallet_Handler,
		},
		{
			MethodName: "GetWallet",
			Handler:    _WalletService_GetWallet_Handler,
		},
		{
			MethodName: "InitiateCharge",
			Handler:    _WalletService_InitiateCharge_Handler,
		},
		{
			MethodName: "RedeemGiftCard",
			Handler:    _WalletService_RedeemGiftCard_Handler,
		},
		{
			MethodName: "ListLedger",
			Handler:    _WalletService_ListLedger_Handler,
		},
		{
			MethodName: "Debit",
			Handler:    _WalletService_Debit_Handler,
		},
		{
			MethodName: "Credit",
			Handler:    _WalletService_Credit_Handler,
		},
		{
			MethodName: "Transfer",
			Handler:    _WalletService_Transfer_Handler,
		},
		{
			MethodName: "HoldFunds",
			Handler:    _WalletService_HoldFunds_Handler,
		},
		{
			MethodName: "CaptureHold",
			Handler:    _WalletService_CaptureHold_Handler,
		},
		{
			MethodName: "ReleaseHold",
			Handler:    _WalletService_ReleaseHold_Handler,
		},
		{
			MethodName: "ListHolds",
			Handler:    _WalletService_ListHolds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "arcadia/wallet/v1/wallet.proto",
}

const (
	GiftCardService_IssueGiftCards_FullMethodName = "/arcadia.wallet.v1.GiftCardService/IssueGiftCards"
	GiftCardService_GetGiftCard_FullMethodName    = "/arcadia.wallet.v1.GiftCardService/GetGiftCard"
	GiftCardService_ListGiftCards_FullMethodName  = "/arcadia.wallet.v1.GiftCardService/ListGiftCards"
	GiftCardService_RevokeGiftCard_FullMethodName = "/arcadia.wallet.v1.GiftCardService/RevokeGiftCard"
)

// GiftCardServiceClient is the client API for GiftCardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GiftCardServiceClient interface {
	IssueGiftCards(ctx context.Context, in *IssueGiftCardsRequest, opts ...grpc.CallOption) (*IssueGiftCardsResponse, error)
	GetGiftCard(ctx context.Context, in *GetGiftCardRequest, opts ...grpc.CallOption) (*GetGiftCardResponse, error)
	ListGiftCards(ctx context.Context, in *ListGiftCardsRequest, opts ...grpc.CallOption) (*ListGiftCardsResponse, error)
	RevokeGiftCard(ctx context.Context, in *RevokeGiftCardRequest, opts ...grpc.CallOption) (*RevokeGiftCardResponse, error)
}

type giftCardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGiftCardServiceClient(cc grpc.ClientConnInterface) GiftCardServiceClient {
	return &giftCardServiceClient{cc}
}

func (c *giftCardServiceClient) IssueGiftCards(ctx context.Context, in *IssueGiftCardsRequest, opts ...grpc.CallOption) (*IssueGiftCardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueGiftCardsResponse)
	err := c.cc.Invoke(ctx, GiftCardService_IssueGiftCards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *giftCardServiceClient) GetGiftCard(ctx context.Context, in *GetGiftCardRequest, opts ...grpc.CallOption) (*GetGiftCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGiftCardResponse)
	err := c.cc.Invoke(ctx, GiftCardService_GetGiftCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *giftCardServiceClient) ListGiftCards(ctx context.Context, in *ListGiftCardsRequest, opts ...grpc.CallOption) (*ListGiftCardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGiftCardsResponse)
	err := c.cc.Invoke(ctx, GiftCardService_ListGiftCards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *giftCardServiceClient) RevokeGiftCard(ctx context.Context, in *RevokeGiftCardRequest, opts ...grpc.CallOption) (*RevokeGiftCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeGiftCardResponse)
	err := c.cc.Invoke(ctx, GiftCardService_RevokeGiftCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GiftCardServiceServer is the server API for GiftCardService service.
// All implementations should embed UnimplementedGiftCardServiceServer
// for forward compatibility.
type GiftCardServiceServer interface {
	IssueGiftCards(context.Context, *IssueGiftCardsRequest) (*IssueGiftCardsResponse, error)
	GetGiftCard(context.Context, *GetGiftCardRequest) (*GetGiftCardResponse, error)
	ListGiftCards(context.Context, *ListGiftCardsRequest) (*ListGiftCardsResponse, error)
	RevokeGiftCard(context.Context, *RevokeGiftCardRequest) (*RevokeGiftCardResponse, error)
}

// UnimplementedGiftCardServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGiftCardServiceServer struct{}

func (UnimplementedGiftCardServiceServer) IssueGiftCards(context.Context, *IssueGiftCardsRequest) (*IssueGiftCardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueGiftCards not implemented")
}
func (UnimplementedGiftCardServiceServer) GetGiftCard(context.Context, *GetGiftCardRequest) (*GetGiftCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGiftCard not implemented")
}
func (UnimplementedGiftCardServiceServer) ListGiftCards(context.Context, *ListGiftCardsRequest) (*ListGiftCardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGiftCards not implemented")
}
func (UnimplementedGiftCardServiceServer) RevokeGiftCard(context.Context, *RevokeGiftCardRequest) (*RevokeGiftCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeGiftCard not implemented")
}
func (UnimplementedGiftCardServiceServer) testEmbeddedByValue() {}

// UnsafeGiftCardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GiftCardServiceServer will
// result in compilation errors.
type UnsafeGiftCardServiceServer interface {
	mustEmbedUnimplementedGiftCardServiceServer()
}

func RegisterGiftCardServiceServer(s grpc.ServiceRegistrar, srv GiftCardServiceServer) {
	// If the following call pancis, it indicates UnimplementedGiftCardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GiftCardService_ServiceDesc, srv)
}

func _GiftCardService_IssueGiftCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueGiftCardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GiftCardServiceServer).IssueGiftCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GiftCardService_IssueGiftCards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GiftCardServiceServer).IssueGiftCards(ctx, req.(*IssueGiftCardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GiftCardService_GetGiftCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGiftCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GiftCardServiceServer).GetGiftCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GiftCardService_GetGiftCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GiftCardServiceServer).GetGiftCard(ctx, req.(*GetGiftCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GiftCardService_ListGiftCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGiftCardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GiftCardServiceServer).ListGiftCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GiftCardService_ListGiftCards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GiftCardServiceServer).ListGiftCards(ctx, req.(*ListGiftCardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GiftCardService_RevokeGiftCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeGiftCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GiftCardServiceServer).RevokeGiftCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GiftCardService_RevokeGiftCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GiftCardServiceServer).RevokeGiftCard(ctx, req.(*RevokeGiftCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GiftCardService_ServiceDesc is the grpc.ServiceDesc for GiftCardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GiftCardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arcadia.wallet.v1.GiftCardService",
	HandlerType: (*GiftCardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueGiftCards",
			Handler:    _GiftCardService_IssueGiftCards_Handler,
		},
		{
			MethodName: "GetGiftCard",
			Handler:    _GiftCardService_GetGiftCard_Handler,
		},
		{
			MethodName: "ListGiftCards",
			Handler:    _GiftCardService_ListGiftCards_Handler,
		},
		{
			MethodName: "RevokeGiftCard",
			Handler:    _GiftCardService_RevokeGiftCard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "arcadia/wallet/v1/wallet.proto",
}

const (
	DiscountService_IssueDiscountCode_FullMethodName  = "/arcadia.wallet.v1.DiscountService/IssueDiscountCode"
	DiscountService_PreviewDiscount_FullMethodName    = "/arcadia.wallet.v1.DiscountService/PreviewDiscount"
	DiscountService_RedeemDiscountCode_FullMethodName = "/arcadia.wallet.v1.DiscountService/RedeemDiscountCode"
	DiscountService_GetDiscountCode_FullMethodName    = "/arcadia.wallet.v1.DiscountService/GetDiscountCode"
)

// DiscountServiceClient is the client API for DiscountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiscountServiceClient interface {
	IssueDiscountCode(ctx context.Context, in *IssueDiscountCodeRequest, opts ...grpc.CallOption) (*IssueDiscountCodeResponse, error)
	// Computes what a code would do to an order without consuming it. Safe to
	// call from the Store service on every checkout preview.
	PreviewDiscount(ctx context.Context, in *PreviewDiscountRequest, opts ...grpc.CallOption) (*PreviewDiscountResponse, error)
	// Consumes one redemption of the code. Idempotent per reference_id.
	RedeemDiscountCode(ctx context.Context, in *RedeemDiscountCodeRequest, opts ...grpc.CallOption) (*RedeemDiscountCodeResponse, error)
	GetDiscountCode(ctx context.Context, in *GetDiscountCodeRequest, opts ...grpc.CallOption) (*GetDiscountCodeResponse, error)
}

type discountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscountServiceClient(cc grpc.ClientConnInterface) DiscountServiceClient {
	return &discountServiceClient{cc}
}

func (c *discountServiceClient) IssueDiscountCode(ctx context.Context, in *IssueDiscountCodeRequest, opts ...grpc.CallOption) (*IssueDiscountCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueDiscountCodeResponse)
	err := c.cc.Invoke(ctx, DiscountService_IssueDiscountCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discountServiceClient) PreviewDiscount(ctx context.Context, in *PreviewDiscountRequest, opts ...grpc.CallOption) (*PreviewDiscountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreviewDiscountResponse)
	err := c.cc.Invoke(ctx, DiscountService_PreviewDiscount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discountServiceClient) RedeemDiscountCode(ctx context.Context, in *RedeemDiscountCodeRequest, opts ...grpc.CallOption) (*RedeemDiscountCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RedeemDiscountCodeResponse)
	err := c.cc.Invoke(ctx, DiscountService_RedeemDiscountCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discountServiceClient) GetDiscountCode(ctx context.Context, in *GetDiscountCodeRequest, opts ...grpc.CallOption) (*GetDiscountCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiscountCodeResponse)
	err := c.cc.Invoke(ctx, DiscountService_GetDiscountCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscountServiceServer is the server API for DiscountService service.
// All implementations should embed UnimplementedDiscountServiceServer
// for forward compatibility.
type DiscountServiceServer interface {
	IssueDiscountCode(context.Context, *IssueDiscountCodeRequest) (*IssueDiscountCodeResponse, error)
	// Computes what a code would do to an order without consuming it. Safe to
	// call from the Store service on every checkout preview.
	PreviewDiscount(context.Context, *PreviewDiscountRequest) (*PreviewDiscountResponse, error)
	// Consumes one redemption of the code. Idempotent per reference_id.
	RedeemDiscountCode(context.Context, *RedeemDiscountCodeRequest) (*RedeemDiscountCodeResponse, error)
	GetDiscountCode(context.Context, *GetDiscountCodeRequest) (*GetDiscountCodeResponse, error)
}

// UnimplementedDiscountServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiscountServiceServer struct{}

func (UnimplementedDiscountServiceServer) IssueDiscountCode(context.Context, *IssueDiscountCodeRequest) (*IssueDiscountCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueDiscountCode not implemented")
}
func (UnimplementedDiscountServiceServer) PreviewDiscount(context.Context, *PreviewDiscountRequest) (*PreviewDiscountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreviewDiscount not implemented")
}
func (UnimplementedDiscountServiceServer) RedeemDiscountCode(context.Context, *RedeemDiscountCodeRequest) (*RedeemDiscountCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RedeemDiscountCode not implemented")
}
func (UnimplementedDiscountServiceServer) GetDiscountCode(context.Context, *GetDiscountCodeRequest) (*GetDiscountCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDiscountCode not implemented")
}
func (UnimplementedDiscountServiceServer) testEmbeddedByValue() {}

// UnsafeDiscountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiscountServiceServer will
// result in compilation errors.
type UnsafeDiscountServiceServer interface {
	mustEmbedUnimplementedDiscountServiceServer()
}

func RegisterDiscountServiceServer(s grpc.ServiceRegistrar, srv DiscountServiceServer) {
	// If the following call pancis, it indicates UnimplementedDiscountServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiscountService_ServiceDesc, srv)
}

func _DiscountService_IssueDiscountCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueDiscountCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscountServiceServer).IssueDiscountCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscountService_IssueDiscountCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscountServiceServer).IssueDiscountCode(ctx, req.(*IssueDiscountCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscountService_PreviewDiscount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreviewDiscountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscountServiceServer).PreviewDiscount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscountService_PreviewDiscount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscountServiceServer).PreviewDiscount(ctx, req.(*PreviewDiscountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscountService_RedeemDiscountCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedeemDiscountCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscountServiceServer).RedeemDiscountCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscountService_RedeemDiscountCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscountServiceServer).RedeemDiscountCode(ctx, req.(*RedeemDiscountCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscountService_GetDiscountCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiscountCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscountServiceServer).GetDiscountCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscountService_GetDiscountCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscountServiceServer).GetDiscountCode(ctx, req.(*GetDiscountCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiscountService_ServiceDesc is the grpc.ServiceDesc for DiscountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiscountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arcadia.wallet.v1.DiscountService",
	HandlerType: (*DiscountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueDiscountCode",
			Handler:    _DiscountService_IssueDiscountCode_Handler,
		},
		{
			MethodName: "PreviewDiscount",
			Handler:    _DiscountService_PreviewDiscount_Handler,
		},
		{
			MethodName: "RedeemDiscountCode",
			Handler:    _DiscountService_RedeemDiscountCode_Handler,
		},
		{
			MethodName: "GetDiscountCode",
			Handler:    _DiscountService_GetDiscountCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "arcadia/wallet/v1/wallet.proto",
}

const (
	WalletAdminService_Reconcile_FullMethodName      = "/arcadia.wallet.v1.WalletAdminService/Reconcile"
	WalletAdminService_AccrueInterest_FullMethodName = "/arcadia.wallet.v1.WalletAdminService/AccrueInterest"
	WalletAdminService_FreezeWallet_FullMethodName   = "/arcadia.wallet.v1.WalletAdminService/FreezeWallet"
	WalletAdminService_UnfreezeWallet_FullMethodName = "/arcadia.wallet.v1.WalletAdminService/UnfreezeWallet"
	WalletAdminService_Adjust_FullMethodName         = "/arcadia.wallet.v1.WalletAdminService/Adjust"
)

// WalletAdminServiceClient is the client API for WalletAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalletAdminServiceClient interface {
	// Verifies that every wallet balance equals the sum of its ledger entries.
	// Any mismatch is a P1 incident (see the SLO table in the architecture doc).
	Reconcile(ctx context.Context, in *ReconcileRequest, opts ...grpc.CallOption) (*ReconcileResponse, error)
	// Runs an interest accrual cycle over eligible balances. Normally invoked by
	// the internal scheduler; exposed for manual replay and testing.
	AccrueInterest(ctx context.Context, in *AccrueInterestRequest, opts ...grpc.CallOption) (*AccrueInterestResponse, error)
	FreezeWallet(ctx context.Context, in *FreezeWalletRequest, opts ...grpc.CallOption) (*FreezeWalletResponse, error)
	UnfreezeWallet(ctx context.Context, in *UnfreezeWalletRequest, opts ...grpc.CallOption) (*UnfreezeWalletResponse, error)
	// Manual balance correction. Always writes a LEDGER_REASON_ADJUSTMENT entry
	// attributed to the calling operator.
	Adjust(ctx context.Context, in *AdjustRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
}

type walletAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletAdminServiceClient(cc grpc.ClientConnInterface) WalletAdminServiceClient {
	return &walletAdminServiceClient{cc}
}

func (c *walletAdminServiceClient) Reconcile(ctx context.Context, in *ReconcileRequest, opts ...grpc.CallOption) (*ReconcileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReconcileResponse)
	err := c.cc.Invoke(ctx, WalletAdminService_Reconcile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletAdminServiceClient) AccrueInterest(ctx context.Context, in *AccrueInterestRequest, opts ...grpc.CallOption) (*AccrueInterestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccrueInterestResponse)
	err := c.cc.Invoke(ctx, WalletAdminService_AccrueInterest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletAdminServiceClient) FreezeWallet(ctx context.Context, in *FreezeWalletRequest, opts ...grpc.CallOption) (*FreezeWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FreezeWalletResponse)
	err := c.cc.Invoke(ctx, WalletAdminService_FreezeWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletAdminServiceClient) UnfreezeWallet(ctx context.Context, in *UnfreezeWalletRequest, opts ...grpc.CallOption) (*UnfreezeWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnfreezeWalletResponse)
	err := c.cc.Invoke(ctx, WalletAdminService_UnfreezeWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletAdminServiceClient) Adjust(ctx context.Context, in *AdjustRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, WalletAdminService_Adjust_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletAdminServiceServer is the server API for WalletAdminService service.
// All implementations should embed UnimplementedWalletAdminServiceServer
// for forward compatibility.
type WalletAdminServiceServer interface {
	// Verifies that every wallet balance equals the sum of its ledger entries.
	// Any mismatch is a P1 incident (see the SLO table in the architecture doc).
	Reconcile(context.Context, *ReconcileRequest) (*ReconcileResponse, error)
	// Runs an interest accrual cycle over eligible balances. Normally invoked by
	// the internal scheduler; exposed for manual replay and testing.
	AccrueInterest(context.Context, *AccrueInterestRequest) (*AccrueInterestResponse, error)
	FreezeWallet(context.Context, *FreezeWalletRequest) (*FreezeWalletResponse, error)
	UnfreezeWallet(context.Context, *UnfreezeWalletRequest) (*UnfreezeWalletResponse, error)
	// Manual balance correction. Always writes a LEDGER_REASON_ADJUSTMENT entry
	// attributed to the calling operator.
	Adjust(context.Context, *AdjustRequest) (*TransactionResponse, error)
}

// UnimplementedWalletAdminServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWalletAdminServiceServer struct{}

func (UnimplementedWalletAdminServiceServer) Reconcile(context.Context, *ReconcileRequest) (*ReconcileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reconcile not implemented")
}
func (UnimplementedWalletAdminServiceServer) AccrueInterest(context.Context, *AccrueInterestRequest) (*AccrueInterestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccrueInterest not implemented")
}
func (UnimplementedWalletAdminServiceServer) FreezeWallet(context.Context, *FreezeWalletRequest) (*FreezeWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FreezeWallet not implemented")
}
func (UnimplementedWalletAdminServiceServer) UnfreezeWallet(context.Context, *UnfreezeWalletRequest) (*UnfreezeWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnfreezeWallet not implemented")
}
func (UnimplementedWalletAdminServiceServer) Adjust(context.Context, *AdjustRequest) (*TransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Adjust not implemented")
}
func (UnimplementedWalletAdminServiceServer) testEmbeddedByValue() {}

// UnsafeWalletAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletAdminServiceServer will
// result in compilation errors.
type UnsafeWalletAdminServiceServer interface {
	mustEmbedUnimplementedWalletAdminServiceServer()
}

func RegisterWalletAdminServiceServer(s grpc.ServiceRegistrar, srv WalletAdminServiceServer) {
	// If the following call pancis, it indicates UnimplementedWalletAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WalletAdminService_ServiceDesc, srv)
}

func _WalletAdminService_Reconcile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconcileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletAdminServiceServer).Reconcile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletAdminService_Reconcile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletAdminServiceServer).Reconcile(ctx, req.(*ReconcileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletAdminService_AccrueInterest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccrueInterestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletAdminServiceServer).AccrueInterest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletAdminService_AccrueInterest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletAdminServiceServer).AccrueInterest(ctx, req.(*AccrueInterestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletAdminService_FreezeWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FreezeWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletAdminServiceServer).FreezeWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletAdminService_FreezeWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletAdminServiceServer).FreezeWallet(ctx, req.(*FreezeWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletAdminService_UnfreezeWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnfreezeWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletAdminServiceServer).UnfreezeWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletAdminService_UnfreezeWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletAdminServiceServer).UnfreezeWallet(ctx, req.(*UnfreezeWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletAdminService_Adjust_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdjustRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletAdminServiceServer).Adjust(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletAdminService_Adjust_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletAdminServiceServer).Adjust(ctx, req.(*AdjustRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletAdminService_ServiceDesc is the grpc.ServiceDesc for WalletAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arcadia.wallet.v1.WalletAdminService",
	HandlerType: (*WalletAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reconcile",
			Handler:    _WalletAdminService_Reconcile_Handler,
		},
		{
			MethodName: "AccrueInterest",
			Handler:    _WalletAdminService_AccrueInterest_Handler,
		},
		{
			MethodName: "FreezeWallet",
			Handler:    _WalletAdminService_FreezeWallet_Handler,
		},
		{
			MethodName: "UnfreezeWallet",
			Handler:    _WalletAdminService_UnfreezeWallet_Handler,
		},
		{
			MethodName: "Adjust",
			Handler:    _WalletAdminService_Adjust_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "arcadia/wallet/v1/wallet.proto",
}
