// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: arcadia/payment/v1/payment.proto

package paymentv1

import (
	v1 "github.com/MS-Arcadia/wallet-service/internal/pb/arcadia/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PaymentIntentState is the state machine of a single bank top-up attempt.
//
//	CREATED ──► PENDING ──► CONFIRMED
//	               │  └────► FAILED
//	               └───────► EXPIRED
//	CREATED/PENDING ──────► CANCELED
//
// CONFIRMED, FAILED, EXPIRED and CANCELED are terminal.
type PaymentIntentState int32

const (
	PaymentIntentState_PAYMENT_INTENT_STATE_UNSPECIFIED PaymentIntentState = 0
	PaymentIntentState_PAYMENT_INTENT_STATE_CREATED     PaymentIntentState = 1
	PaymentIntentState_PAYMENT_INTENT_STATE_PENDING     PaymentIntentState = 2
	PaymentIntentState_PAYMENT_INTENT_STATE_CONFIRMED   PaymentIntentState = 3
	PaymentIntentState_PAYMENT_INTENT_STATE_FAILED      PaymentIntentState = 4
	PaymentIntentState_PAYMENT_INTENT_STATE_EXPIRED     PaymentIntentState = 5
	PaymentIntentState_PAYMENT_INTENT_STATE_CANCELED    PaymentIntentState = 6
)

// Enum value maps for PaymentIntentState.
var (
	PaymentIntentState_name = map[int32]string{
		0: "PAYMENT_INTENT_STATE_UNSPECIFIED",
		1: "PAYMENT_INTENT_STATE_CREATED",
		2: "PAYMENT_INTENT_STATE_PENDING",
		3: "PAYMENT_INTENT_STATE_CONFIRMED",
		4: "PAYMENT_INTENT_STATE_FAILED",
		5: "PAYMENT_INTENT_STATE_EXPIRED",
		6: "PAYMENT_INTENT_STATE_CANCELED",
	}
	PaymentIntentState_value = map[string]int32{
		"PAYMENT_INTENT_STATE_UNSPECIFIED": 0,
		"PAYMENT_INTENT_STATE_CREATED":     1,
		"PAYMENT_INTENT_STATE_PENDING":     2,
		"PAYMENT_INTENT_STATE_CONFIRMED":   3,
		"PAYMENT_INTENT_STATE_FAILED":      4,
		"PAYMENT_INTENT_STATE_EXPIRED":     5,
		"PAYMENT_INTENT_STATE_CANCELED":    6,
	}
)

func (x PaymentIntentState) Enum() *PaymentIntentState {
	p := new(PaymentIntentState)
	*p = x
	return p
}

func (x PaymentIntentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentIntentState) Descriptor() protoreflect.EnumDescriptor {
	return file_arcadia_payment_v1_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentIntentState) Type() protoreflect.EnumType {
	return &file_arcadia_payment_v1_payment_proto_enumTypes[0]
}

func (x PaymentIntentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentIntentState.Descriptor instead.
func (PaymentIntentState) EnumDescriptor() ([]byte, []int) {
	return file_arcadia_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

type PaymentPurpose int32

const (
	PaymentPurpose_PAYMENT_PURPOSE_UNSPECIFIED  PaymentPurpose = 0
	PaymentPurpose_PAYMENT_PURPOSE_WALLET_TOPUP PaymentPurpose = 1
)

// Enum value maps for PaymentPurpose.
var (
	PaymentPurpose_name = map[int32]string{
		0: "PAYMENT_PURPOSE_UNSPECIFIED",
		1: "PAYMENT_PURPOSE_WALLET_TOPUP",
	}
	PaymentPurpose_value = map[string]int32{
		"PAYMENT_PURPOSE_UNSPECIFIED":  0,
		"PAYMENT_PURPOSE_WALLET_TOPUP": 1,
	}
)

func (x PaymentPurpose) Enum() *PaymentPurpose {
	p := new(PaymentPurpose)
	*p = x
	return p
}

func (x PaymentPurpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentPurpose) Descriptor() protoreflect.EnumDescriptor {
	return file_arcadia_payment_v1_payment_proto_enumTypes[1].Descriptor()
}

func (PaymentPurpose) Type() protoreflect.EnumType {
	return &file_arcadia_payment_v1_payment_proto_enumTypes[1]
}

func (x PaymentPurpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentPurpose.Descriptor instead.
func (PaymentPurpose) EnumDescriptor() ([]byte, []int) {
	return file_arcadia_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

type PaymentIntent struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId  string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount  *v1.Money              `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	State   PaymentIntentState     `protobuf:"varint,4,opt,name=state,proto3,enum=arcadia.payment.v1.PaymentIntentState" json:"state,omitempty"`
	Purpose PaymentPurpose         `protobuf:"varint,5,opt,name=purpose,proto3,enum=arcadia.payment.v1.PaymentPurpose" json:"purpose,omitempty"`
	// Provider-side identifier (authority / token / reference number).
	GatewayRef  string `protobuf:"bytes,6,opt,name=gateway_ref,json=gatewayRef,proto3" json:"gateway_ref,omitempty"`
	GatewayName string `protobuf:"bytes,7,opt,name=gateway_name,json=gatewayName,proto3" json:"gateway_name,omitempty"`
	// URL the user must visit to authorise the payment.
	RedirectUrl string `protobuf:"bytes,8,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	ReturnUrl   string `protobuf:"bytes,9,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	// Bank's own transaction id, only present once settled.
	BankReference string `protobuf:"bytes,10,opt,name=bank_reference,json=bankReference,proto3" json:"bank_reference,omitempty"`
	FailureCode   string `protobuf:"bytes,11,opt,name=failure_code,json=failureCode,proto3" json:"failure_code,omitempty"`
	FailureReason string `protobuf:"bytes,12,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	CreatedAt     string `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ExpiresAt     string `protobuf:"bytes,15,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	SettledAt     string `protobuf:"bytes,16,opt,name=settled_at,json=settledAt,proto3" json:"settled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentIntent) Reset() {
	*x = PaymentIntent{}
	mi := &file_arcadia_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentIntent) ProtoMessage() {}

func (x *PaymentIntent) ProtoReflect() protoreflect.Message {
	mi := &file_arcadia_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentIntent.ProtoReflect.Descriptor instead.
func (*PaymentIntent) Descriptor() ([]byte, []int) {
	return file_arcadia_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentIntent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentIntent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PaymentIntent) GetAmount() *v1.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *PaymentIntent) GetState() PaymentIntentState {
	if x != nil {
		return x.State
	}
	return PaymentIntentState_PAYMENT_INTENT_STATE_UNSPECIFIED
}

func (x *PaymentIntent) GetPurpose() PaymentPurpose {
	if x != nil {
		return x.Purpose
	}
	return PaymentPurpose_PAYMENT_PURPOSE_UNSPECIFIED
}

func (x *PaymentIntent) GetGatewayRef() string {
	if x != nil {
		return x.GatewayRef
	}
	return ""
}

func (x *PaymentIntent) GetGatewayName() string {
	if x != nil {
		return x.GatewayName
	}
	return ""
}

func (x *PaymentIntent) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

func (x *PaymentIntent) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

func (x *PaymentIntent) GetBankReference() string {
	if x != nil {
		return x.BankReference
	}
	return ""
}

func (x *PaymentIntent) GetFailureCode() string {
	if x != nil {
		return x.FailureCode
	}
	return ""
}

func (x *PaymentIntent) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *PaymentIntent) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PaymentIntent) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *PaymentIntent) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *PaymentIntent) GetSettledAt() string {
	if x != nil {
		return x.SettledAt
	}
	return ""
}

type InitiatePaymentRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	UserId    string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount    *v1.Money              `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Purpose   PaymentPurpose         `protobuf:"varint,3,opt,name=purpose,proto3,enum=arcadia.payment.v1.PaymentPurpose" json:"purpose,omitempty"`
	ReturnUrl string                 `protobuf:"bytes,4,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	// Free-form key/value pairs echoed back on the resulting events.
	Metadata       map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IdempotencyKey string            `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InitiatePaymentRequest) Reset() {
	*x = InitiatePaymentRequest{}
	mi := &file_arcadia_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiatePaymentRequest) ProtoMessage() {}

func (x *InitiatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arcadia_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiatePaymentRequest.ProtoReflect.Descriptor instead.
func (*InitiatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_arcadia_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *InitiatePaymentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InitiatePaymentRequest) GetAmount() *v1.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *InitiatePaymentRequest) GetPurpose() PaymentPurpose {
	if x != nil {
		return x.Purpose
	}
	return PaymentPurpose_PAYMENT_PURPOSE_UNSPECIFIED
}

func (x *InitiatePaymentRequest) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

func (x *InitiatePaymentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *InitiatePaymentRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type InitiatePaymentResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Intent           *PaymentIntent         `protobuf:"bytes,1,opt,name=intent,proto3" json:"intent,omitempty"`
	IdempotentReplay bool                   `protobuf:"varint,2,opt,name=idempotent_replay,json=idempotentReplay,proto3" json:"idempotent_replay,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InitiatePaymentResponse) Reset() {
	*x = InitiatePaymentResponse{}
	mi := &file_arcadia_payment_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiatePaymentResponse) ProtoMessage() {}

func (x *InitiatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arcadia_payment_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiatePaymentResponse.ProtoReflect.Descriptor instead.
func (*InitiatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_arcadia_payment_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *InitiatePaymentResponse) GetIntent() *PaymentIntent {
	if x != nil {
		return x.Intent
	}
	return nil
}

func (x *InitiatePaymentResponse) GetIdempotentReplay() bool {
	if x != nil {
		return x.IdempotentReplay
	}
	return false
}

type GetPaymentIntentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentIntentRequest) Reset() {
	*x = GetPaymentIntentRequest{}
	mi := &file_arcadia_payment_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentIntentRequest) ProtoMessage() {}

func (x *GetPaymentIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arcadia_payment_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentIntentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentIntentRequest) Descriptor() ([]byte, []int) {
	return file_arcadia_payment_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *GetPaymentIntentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPaymentIntentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Intent        *PaymentIntent         `protobuf:"bytes,1,opt,name=intent,proto3" json:"intent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentIntentResponse) Reset() {
	*x = GetPaymentIntentResponse{}
	mi := &file_arcadia_payment_v1_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentIntentResponse) ProtoMessage() {}

func (x *GetPaymentIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arcadia_payment_v1_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentIntentResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentIntentResponse) Descriptor() ([]byte, []int) {
	return file_arcadia_payment_v1_payment_proto_rawDescGZIP(), []int{4}
}

func (x *GetPaymentIntentResponse) GetIntent() *PaymentIntent {
	if x != nil {
		return x.Intent
	}
	return nil
}

type ListPaymentIntentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	State         PaymentIntentState     `protobuf:"varint,2,opt,name=state,proto3,enum=arcadia.payment.v1.PaymentIntentState" json:"state,omitempty"`
	Page          *v1.PageRequest        `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	Range         *v1.TimeRange          `protobuf:"bytes,4,opt,name=range,proto3" json:"range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentIntentsRequest) Reset() {
	*x = ListPaymentIntentsRequest{}
	mi := &file_arcadia_payment_v1_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentIntentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentIntentsRequest) ProtoMessage() {}

func (x *ListPaymentIntentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arcadia_payment_v1_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentIntentsRequest.ProtoReflect.Descriptor instead.
func (*ListPaymentIntentsRequest) Descriptor() ([]byte, []int) {
	return file_arcadia_payment_v1_payment_proto_rawDescGZIP(), []int{5}
}

func (x *ListPaymentIntentsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListPaymentIntentsRequest) GetState() PaymentIntentState {
	if x != nil {
		return x.State
	}
	return PaymentIntentState_PAYMENT_INTENT_STATE_UNSPECIFIED
}

func (x *ListPaymentIntentsRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListPaymentIntentsRequest) GetRange() *v1.TimeRange {
	if x != nil {
		return x.Range
	}
	return nil
}

type ListPaymentIntentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Intents       []*PaymentIntent       `protobuf:"bytes,1,rep,name=intents,proto3" json:"intents,omitempty"`
	Page          *v1.PageResponse       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentIntentsResponse) Reset() {
	*x = ListPaymentIntentsResponse{}
	mi := &file_arcadia_payment_v1_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentIntentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentIntentsResponse) ProtoMessage() {}

func (x *ListPaymentIntentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arcadia_payment_v1_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentIntentsResponse.ProtoReflect.Descriptor instead.
func (*ListPaymentIntentsResponse) Descriptor() ([]byte, []int) {
	return file_arcadia_payment_v1_payment_proto_rawDescGZIP(), []int{6}
}

func (x *ListPaymentIntentsResponse) GetIntents() []*PaymentIntent {
	if x != nil {
		return x.Intents
	}
	return nil
}

func (x *ListPaymentIntentsResponse) GetPage() *v1.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type CancelPaymentIntentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPaymentIntentRequest) Reset() {
	*x = CancelPaymentIntentRequest{}
	mi := &file_arcadia_payment_v1_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPaymentIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPaymentIntentRequest) ProtoMessage() {}

func (x *CancelPaymentIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arcadia_payment_v1_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPaymentIntentRequest.ProtoReflect.Descriptor instead.
func (*CancelPaymentIntentRequest) Descriptor() ([]byte, []int) {
	return file_arcadia_payment_v1_payment_proto_rawDescGZIP(), []int{7}
}

func (x *CancelPaymentIntentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CancelPaymentIntentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelPaymentIntentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Intent        *PaymentIntent         `protobuf:"bytes,1,opt,name=intent,proto3" json:"intent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPaymentIntentResponse) Reset() {
	*x = CancelPaymentIntentResponse{}
	mi := &file_arcadia_payment_v1_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPaymentIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPaymentIntentResponse) ProtoMessage() {}

func (x *CancelPaymentIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arcadia_payment_v1_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPaymentIntentResponse.ProtoReflect.Descriptor instead.
func (*CancelPaymentIntentResponse) Descriptor() ([]byte, []int) {
	return file_arcadia_payment_v1_payment_proto_rawDescGZIP(), []int{8}
}

func (x *CancelPaymentIntentResponse) GetIntent() *PaymentIntent {
	if x != nil {
		return x.Intent
	}
	return nil
}

type VerifyPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPaymentRequest) Reset() {
	*x = VerifyPaymentRequest{}
	mi := &file_arcadia_payment_v1_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPaymentRequest) ProtoMessage() {}

func (x *VerifyPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arcadia_payment_v1_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPaymentRequest.ProtoReflect.Descriptor instead.
func (*VerifyPaymentRequest) Descriptor() ([]byte, []int) {
	return file_arcadia_payment_v1_payment_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyPaymentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type VerifyPaymentResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Intent *PaymentIntent         `protobuf:"bytes,1,opt,name=intent,proto3" json:"intent,omitempty"`
	// False when the bank still reports the payment as in-flight.
	Settled       bool `protobuf:"varint,2,opt,name=settled,proto3" json:"settled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPaymentResponse) Reset() {
	*x = VerifyPaymentResponse{}
	mi := &file_arcadia_payment_v1_payment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPaymentResponse) ProtoMessage() {}

func (x *VerifyPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arcadia_payment_v1_payment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPaymentResponse.ProtoReflect.Descriptor instead.
func (*VerifyPaymentResponse) Descriptor() ([]byte, []int) {
	return file_arcadia_payment_v1_payment_proto_rawDescGZIP(), []int{10}
}

func (x *VerifyPaymentResponse) GetIntent() *PaymentIntent {
	if x != nil {
		return x.Intent
	}
	return nil
}

func (x *VerifyPaymentResponse) GetSettled() bool {
	if x != nil {
		return x.Settled
	}
	return false
}

var File_arcadia_payment_v1_payment_proto protoreflect.FileDescriptor

const file_arcadia_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	" arcadia/payment/v1/payment.proto\x12\x12arcadia.payment.v1\x1a\x1earcadia/common/v1/common.proto\"\xd9\x04\n" +
	"\rPaymentIntent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x120\n" +
	"\x06amount\x18\x03 \x01(\v2\x18.arcadia.common.v1.MoneyR\x06amount\x12<\n" +
	"\x05state\x18\x04 \x01(\x0e2&.arcadia.payment.v1.PaymentIntentStateR\x05state\x12<\n" +
	"\apurpose\x18\x05 \x01(\x0e2\".arcadia.payment.v1.PaymentPurposeR\apurpose\x12\x1f\n" +
	"\vgateway_ref\x18\x06 \x01(\tR\n" +
	"gatewayRef\x12!\n" +
	"\fgateway_name\x18\a \x01(\tR\vgatewayName\x12!\n" +
	"\fredirect_url\x18\b \x01(\tR\vredirectUrl\x12\x1d\n" +
	"\n" +
	"return_url\x18\t \x01(\tR\treturnUrl\x12%\n" +
	"\x0ebank_reference\x18\n" +
	" \x01(\tR\rbankReference\x12!\n" +
	"\ffailure_code\x18\v \x01(\tR\vfailureCode\x12%\n" +
	"\x0efailure_reason\x18\f \x01(\tR\rfailureReason\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x0f \x01(\tR\texpiresAt\x12\x1d\n" +
	"\n" +
	"settled_at\x18\x10 \x01(\tR\tsettledAt\"\xfc\x02\n" +
	"\x16InitiatePaymentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x120\n" +
	"\x06amount\x18\x02 \x01(\v2\x18.arcadia.common.v1.MoneyR\x06amount\x12<\n" +
	"\apurpose\x18\x03 \x01(\x0e2\".arcadia.payment.v1.PaymentPurposeR\apurpose\x12\x1d\n" +
	"\n" +
	"return_url\x18\x04 \x01(\tR\treturnUrl\x12T\n" +
	"\bmetadata\x18\x05 \x03(\v28.arcadia.payment.v1.InitiatePaymentRequest.MetadataEntryR\bmetadata\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x01\n" +
	"\x17InitiatePaymentResponse\x129\n" +
	"\x06intent\x18\x01 \x01(\v2!.arcadia.payment.v1.PaymentIntentR\x06intent\x12+\n" +
	"\x11idempotent_replay\x18\x02 \x01(\bR\x10idempotentReplay\")\n" +
	"\x17GetPaymentIntentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"U\n" +
	"\x18GetPaymentIntentResponse\x129\n" +
	"\x06intent\x18\x01 \x01(\v2!.arcadia.payment.v1.PaymentIntentR\x06intent\"\xda\x01\n" +
	"\x19ListPaymentIntentsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12<\n" +
	"\x05state\x18\x02 \x01(\x0e2&.arcadia.payment.v1.PaymentIntentStateR\x05state\x122\n" +
	"\x04page\x18\x03 \x01(\v2\x1e.arcadia.common.v1.PageRequestR\x04page\x122\n" +
	"\x05range\x18\x04 \x01(\v2\x1c.arcadia.common.v1.TimeRangeR\x05range\"\x8e\x01\n" +
	"\x1aListPaymentIntentsResponse\x12;\n" +
	"\aintents\x18\x01 \x03(\v2!.arcadia.payment.v1.PaymentIntentR\aintents\x123\n" +
	"\x04page\x18\x02 \x01(\v2\x1f.arcadia.common.v1.PageResponseR\x04page\"D\n" +
	"\x1aCancelPaymentIntentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"X\n" +
	"\x1bCancelPaymentIntentResponse\x129\n" +
	"\x06intent\x18\x01 \x01(\v2!.arcadia.payment.v1.PaymentIntentR\x06intent\"&\n" +
	"\x14VerifyPaymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"l\n" +
	"\x15VerifyPaymentResponse\x129\n" +
	"\x06intent\x18\x01 \x01(\v2!.arcadia.payment.v1.PaymentIntentR\x06intent\x12\x18\n" +
	"\asettled\x18\x02 \x01(\bR\asettled*\x88\x02\n" +
	"\x12PaymentIntentState\x12$\n" +
	" PAYMENT_INTENT_STATE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cPAYMENT_INTENT_STATE_CREATED\x10\x01\x12 \n" +
	"\x1cPAYMENT_INTENT_STATE_PENDING\x10\x02\x12\"\n" +
	"\x1ePAYMENT_INTENT_STATE_CONFIRMED\x10\x03\x12\x1f\n" +
	"\x1bPAYMENT_INTENT_STATE_FAILED\x10\x04\x12 \n" +
	"\x1cPAYMENT_INTENT_STATE_EXPIRED\x10\x05\x12!\n" +
	"\x1dPAYMENT_INTENT_STATE_CANCELED\x10\x06*S\n" +
	"\x0ePaymentPurpose\x12\x1f\n" +
	"\x1bPAYMENT_PURPOSE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cPAYMENT_PURPOSE_WALLET_TOPUP\x10\x012\xbe\x04\n" +
	"\x0ePaymentService\x12j\n" +
	"\x0fInitiatePayment\x12*.arcadia.payment.v1.InitiatePaymentRequest\x1a+.arcadia.payment.v1.InitiatePaymentResponse\x12m\n" +
	"\x10GetPaymentIntent\x12+.arcadia.payment.v1.GetPaymentIntentRequest\x1a,.arcadia.payment.v1.GetPaymentIntentResponse\x12s\n" +
	"\x12ListPaymentIntents\x12-.arcadia.payment.v1.ListPaymentIntentsRequest\x1a..arcadia.payment.v1.ListPaymentIntentsResponse\x12v\n" +
	"\x13CancelPaymentIntent\x12..arcadia.payment.v1.CancelPaymentIntentRequest\x1a/.arcadia.payment.v1.CancelPaymentIntentResponse\x12d\n" +
	"\rVerifyPayment\x12(.arcadia.payment.v1.VerifyPaymentRequest\x1a).arcadia.payment.v1.VerifyPaymentResponseBOZMgithub.com/MS-Arcadia/wallet-service/internal/pb/arcadia/payment/v1;paymentv1b\x06proto3"

var (
	file_arcadia_payment_v1_payment_proto_rawDescOnce sync.Once
	file_arcadia_payment_v1_payment_proto_rawDescData []byte
)

func file_arcadia_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_arcadia_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_arcadia_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_arcadia_payment_v1_payment_proto_rawDesc), len(file_arcadia_payment_v1_payment_proto_rawDesc)))
	})
	return file_arcadia_payment_v1_payment_proto_rawDescData
}

var file_arcadia_payment_v1_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_arcadia_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_arcadia_payment_v1_payment_proto_goTypes = []any{
	(PaymentIntentState)(0),             // 0: arcadia.payment.v1.PaymentIntentState
	(PaymentPurpose)(0),                 // 1: arcadia.payment.v1.PaymentPurpose
	(*PaymentIntent)(nil),               // 2: arcadia.payment.v1.PaymentIntent
	(*InitiatePaymentRequest)(nil),      // 3: arcadia.payment.v1.InitiatePaymentRequest
	(*InitiatePaymentResponse)(nil),     // 4: arcadia.payment.v1.InitiatePaymentResponse
	(*GetPaymentIntentRequest)(nil),     // 5: arcadia.payment.v1.GetPaymentIntentRequest
	(*GetPaymentIntentResponse)(nil),    // 6: arcadia.payment.v1.GetPaymentIntentResponse
	(*ListPaymentIntentsRequest)(nil),   // 7: arcadia.payment.v1.ListPaymentIntentsRequest
	(*ListPaymentIntentsResponse)(nil),  // 8: arcadia.payment.v1.ListPaymentIntentsResponse
	(*CancelPaymentIntentRequest)(nil),  // 9: arcadia.payment.v1.CancelPaymentIntentRequest
	(*CancelPaymentIntentResponse)(nil), // 10: arcadia.payment.v1.CancelPaymentIntentResponse
	(*VerifyPaymentRequest)(nil),        // 11: arcadia.payment.v1.VerifyPaymentRequest
	(*VerifyPaymentResponse)(nil),       // 12: arcadia.payment.v1.VerifyPaymentResponse
	nil,                                 // 13: arcadia.payment.v1.InitiatePaymentRequest.MetadataEntry
	(*v1.Money)(nil),                    // 14: arcadia.common.v1.Money
	(*v1.PageRequest)(nil),              // 15: arcadia.common.v1.PageRequest
	(*v1.TimeRange)(nil),                // 16: arcadia.common.v1.TimeRange
	(*v1.PageResponse)(nil),             // 17: arcadia.common.v1.PageResponse
}
var file_arcadia_payment_v1_payment_proto_depIdxs = []int32{
	14, // 0: arcadia.payment.v1.PaymentIntent.amount:type_name -> arcadia.common.v1.Money
	0,  // 1: arcadia.payment.v1.PaymentIntent.state:type_name -> arcadia.payment.v1.PaymentIntentState
	1,  // 2: arcadia.payment.v1.PaymentIntent.purpose:type_name -> arcadia.payment.v1.PaymentPurpose
	14, // 3: arcadia.payment.v1.InitiatePaymentRequest.amount:type_name -> arcadia.common.v1.Money
	1,  // 4: arcadia.payment.v1.InitiatePaymentRequest.purpose:type_name -> arcadia.payment.v1.PaymentPurpose
	13, // 5: arcadia.payment.v1.InitiatePaymentRequest.metadata:type_name -> arcadia.payment.v1.InitiatePaymentRequest.MetadataEntry
	2,  // 6: arcadia.payment.v1.InitiatePaymentResponse.intent:type_name -> arcadia.payment.v1.PaymentIntent
	2,  // 7: arcadia.payment.v1.GetPaymentIntentResponse.intent:type_name -> arcadia.payment.v1.PaymentIntent
	0,  // 8: arcadia.payment.v1.ListPaymentIntentsRequest.state:type_name -> arcadia.payment.v1.PaymentIntentState
	15, // 9: arcadia.payment.v1.ListPaymentIntentsRequest.page:type_name -> arcadia.common.v1.PageRequest
	16, // 10: arcadia.payment.v1.ListPaymentIntentsRequest.range:type_name -> arcadia.common.v1.TimeRange
	2,  // 11: arcadia.payment.v1.ListPaymentIntentsResponse.intents:type_name -> arcadia.payment.v1.PaymentIntent
	17, // 12: arcadia.payment.v1.ListPaymentIntentsResponse.page:type_name -> arcadia.common.v1.PageResponse
	2,  // 13: arcadia.payment.v1.CancelPaymentIntentResponse.intent:type_name -> arcadia.payment.v1.PaymentIntent
	2,  // 14: arcadia.payment.v1.VerifyPaymentResponse.intent:type_name -> arcadia.payment.v1.PaymentIntent
	3,  // 15: arcadia.payment.v1.PaymentService.InitiatePayment:input_type -> arcadia.payment.v1.InitiatePaymentRequest
	5,  // 16: arcadia.payment.v1.PaymentService.GetPaymentIntent:input_type -> arcadia.payment.v1.GetPaymentIntentRequest
	7,  // 17: arcadia.payment.v1.PaymentService.ListPaymentIntents:input_type -> arcadia.payment.v1.ListPaymentIntentsRequest
	9,  // 18: arcadia.payment.v1.PaymentService.CancelPaymentIntent:input_type -> arcadia.payment.v1.CancelPaymentIntentRequest
	11, // 19: arcadia.payment.v1.PaymentService.VerifyPayment:input_type -> arcadia.payment.v1.VerifyPaymentRequest
	4,  // 20: arcadia.payment.v1.PaymentService.InitiatePayment:output_type -> arcadia.payment.v1.InitiatePaymentResponse
	6,  // 21: arcadia.payment.v1.PaymentService.GetPaymentIntent:output_type -> arcadia.payment.v1.GetPaymentIntentResponse
	8,  // 22: arcadia.payment.v1.PaymentService.ListPaymentIntents:output_type -> arcadia.payment.v1.ListPaymentIntentsResponse
	10, // 23: arcadia.payment.v1.PaymentService.CancelPaymentIntent:output_type -> arcadia.payment.v1.CancelPaymentIntentResponse
	12, // 24: arcadia.payment.v1.PaymentService.VerifyPayment:output_type -> arcadia.payment.v1.VerifyPaymentResponse
	20, // [20:25] is the sub-list for method output_type
	15, // [15:20] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_arcadia_payment_v1_payment_proto_init() }
func file_arcadia_payment_v1_payment_proto_init() {
	if File_arcadia_payment_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arcadia_payment_v1_payment_proto_rawDesc), len(file_arcadia_payment_v1_payment_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_arcadia_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_arcadia_payment_v1_payment_proto_depIdxs,
		EnumInfos:         file_arcadia_payment_v1_payment_proto_enumTypes,
		MessageInfos:      file_arcadia_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_arcadia_payment_v1_payment_proto = out.File
	file_arcadia_payment_v1_payment_proto_goTypes = nil
	file_arcadia_payment_v1_payment_proto_depIdxs = nil
}
